import '../models/product_model.dart';

class ProductDbService {
  static final ProductDbService _instance = ProductDbService._internal();
  factory ProductDbService() => _instance;
  ProductDbService._internal();

  final List<Product> _products = [
    // -------------------------------------------------------------
    // CATEGORY: Canned Fish & Seafood (1-15)
    // -------------------------------------------------------------
    Product(
      id: "century_tuna_flakes_oil",
      name: "Century Tuna Flakes in Vegetable Oil",
      brand: "Century Tuna",
      variant: "Flakes in Vegetable Oil",
      category: "Canned Fish",
      imageUrl: "assets/images/century_tuna_oil.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000001234567",
      allergens: ["Fish (Tuna)", "Soy"],
      ingredients: ["Tuna Flakes", "Water", "Soybean Oil", "Seasoning", "Salt"],
      servingInstructions: "Ready to eat. Can be served cold or heated. Perfect for salads, sandwiches, or cooked with onions.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "56g (Approx. 1/3 cup)",
        servingsPerContainer: "3",
        calories: "120 kcal",
        totalFat: "9g",
        saturatedFat: "1.5g",
        transFat: "0g",
        cholesterol: "15mg",
        sodium: "250mg",
        totalCarbohydrate: "0g",
        dietaryFiber: "0g",
        sugars: "0g",
        protein: "10g",
      ),
    ),
    Product(
      id: "century_tuna_hot_spicy",
      name: "Century Tuna Flakes Hot & Spicy",
      brand: "Century Tuna",
      variant: "Hot & Spicy",
      category: "Canned Fish",
      imageUrl: "assets/images/century_tuna_spicy.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000001234568",
      allergens: ["Fish (Tuna)", "Soy", "Wheat"],
      ingredients: ["Tuna Flakes", "Water", "Soybean Oil", "Chili", "Soy Sauce (Wheat, Soybean, Salt, Water)", "Ginger", "Salt", "Spices"],
      servingInstructions: "Ready to eat. Serve hot with steamed rice or use as a spicy tuna pasta base.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "56g (Approx. 1/3 cup)",
        servingsPerContainer: "3",
        calories: "130 kcal",
        totalFat: "10g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "15mg",
        sodium: "290mg",
        totalCarbohydrate: "1g",
        dietaryFiber: "0.5g",
        sugars: "0.5g",
        protein: "9g",
      ),
    ),
    Product(
      id: "century_tuna_calamansi",
      name: "Century Tuna Flakes Calamansi",
      brand: "Century Tuna",
      variant: "Calamansi",
      category: "Canned Fish",
      imageUrl: "assets/images/century_tuna_calamansi.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000001234569",
      allergens: ["Fish (Tuna)", "Soy"],
      ingredients: ["Tuna Flakes", "Water", "Soybean Oil", "Calamansi Extract", "Salt", "Sugar", "Spices"],
      servingInstructions: "Ready to eat. Best served fresh with chopped onions or mixed in a cold salad.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "56g",
        servingsPerContainer: "3",
        calories: "115 kcal",
        totalFat: "8g",
        saturatedFat: "1.2g",
        transFat: "0g",
        cholesterol: "15mg",
        sodium: "260mg",
        totalCarbohydrate: "1g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "10g",
      ),
    ),
    Product(
      id: "555_sardines_tomato_sauce",
      name: "555 Sardines in Tomato Sauce",
      brand: "555",
      variant: "Tomato Sauce",
      category: "Canned Fish",
      imageUrl: "assets/images/555_sardines_tomato.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000002345678",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce (Tomato Paste, Water)", "Salt", "Modified Starch", "Monosodium Glutamate", "Spices"],
      servingInstructions: "Ready to eat. For best taste, sauté with minced garlic and onions.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "75g",
        servingsPerContainer: "2",
        calories: "90 kcal",
        totalFat: "4.5g",
        saturatedFat: "1.5g",
        transFat: "0g",
        cholesterol: "40mg",
        sodium: "320mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0.5g",
        sugars: "1g",
        protein: "10g",
      ),
    ),
    Product(
      id: "555_sardines_tomato_spicy",
      name: "555 Sardines in Tomato Sauce Hot & Spicy",
      brand: "555",
      variant: "Tomato Sauce Hot & Spicy",
      category: "Canned Fish",
      imageUrl: "assets/images/555_sardines_spicy.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000002345679",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce (Tomato Paste, Water)", "Chili", "Salt", "Modified Starch", "MSG", "Spices"],
      servingInstructions: "Sauté with scrambled eggs or serve hot directly over hot rice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "75g",
        servingsPerContainer: "2",
        calories: "95 kcal",
        totalFat: "5g",
        saturatedFat: "1.8g",
        transFat: "0g",
        cholesterol: "40mg",
        sodium: "340mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0.5g",
        sugars: "1g",
        protein: "10g",
      ),
    ),
    Product(
      id: "555_fried_sardines_hot_spicy",
      name: "555 Fried Sardines Hot & Spicy",
      brand: "555",
      variant: "Fried Hot & Spicy",
      category: "Canned Fish",
      imageUrl: "assets/images/555_fried_sardines.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000002345680",
      allergens: ["Fish (Sardines)", "Wheat", "Soy"],
      ingredients: ["Fried Sardines", "Soya Oil", "Water", "Spices", "Chili", "Salt", "Sugar", "MSG"],
      servingInstructions: "Ready to eat. Great with fried rice and vinegar dip.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "75g",
        servingsPerContainer: "2",
        calories: "140 kcal",
        totalFat: "11g",
        saturatedFat: "3g",
        transFat: "0g",
        cholesterol: "30mg",
        sodium: "380mg",
        totalCarbohydrate: "1g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "9g",
      ),
    ),
    Product(
      id: "ligo_sardines_tomato_green",
      name: "Ligo Sardines in Tomato Sauce (Green Can)",
      brand: "Ligo",
      variant: "Tomato Sauce (Ligo Green)",
      category: "Canned Fish",
      imageUrl: "assets/images/ligo_sardines_green.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000003456789",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce (Tomato Paste, Water)", "Salt", "Modified Food Starch", "MSG", "Spices"],
      servingInstructions: "Serve straight from the can, or heat with garlic, onions, and calamansi juice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "77g",
        servingsPerContainer: "2",
        calories: "92 kcal",
        totalFat: "4g",
        saturatedFat: "1.4g",
        transFat: "0g",
        cholesterol: "38mg",
        sodium: "310mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "11g",
      ),
    ),
    Product(
      id: "ligo_sardines_tomato_red",
      name: "Ligo Sardines in Tomato Sauce Extra Hot (Red Can)",
      brand: "Ligo",
      variant: "Tomato Sauce Extra Hot",
      category: "Canned Fish",
      imageUrl: "assets/images/ligo_sardines_red.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000003456790",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce (Tomato Paste, Water)", "Chili Pepper", "Salt", "Spices"],
      servingInstructions: "Ready to eat. Best cooked with diced onions and green chili for extra bite.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "77g",
        servingsPerContainer: "2",
        calories: "95 kcal",
        totalFat: "4.5g",
        saturatedFat: "1.5g",
        transFat: "0g",
        cholesterol: "38mg",
        sodium: "330mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "11g",
      ),
    ),
    Product(
      id: "mega_sardines_tomato",
      name: "Mega Sardines in Tomato Sauce",
      brand: "Mega",
      variant: "Tomato Sauce",
      category: "Canned Fish",
      imageUrl: "assets/images/mega_sardines_tomato.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000004567890",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce (Tomato Paste, Water)", "Salt", "Sugar", "Spices", "MSG"],
      servingInstructions: "Ready to eat. Try cooking it with native pechay leaves and water for a quick soup.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "77g",
        servingsPerContainer: "2",
        calories: "85 kcal",
        totalFat: "3.5g",
        saturatedFat: "1.2g",
        transFat: "0g",
        cholesterol: "35mg",
        sodium: "300mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "11g",
      ),
    ),
    Product(
      id: "mega_sardines_chili",
      name: "Mega Sardines in Tomato Sauce with Chili",
      brand: "Mega",
      variant: "Tomato Sauce with Chili",
      category: "Canned Fish",
      imageUrl: "assets/images/mega_sardines_chili.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000004567891",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce", "Chili", "Salt", "Spices"],
      servingInstructions: "Best served hot over white rice. Sauté with garlic and sliced tomatoes.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "77g",
        servingsPerContainer: "2",
        calories: "90 kcal",
        totalFat: "4g",
        saturatedFat: "1.4g",
        transFat: "0g",
        cholesterol: "35mg",
        sodium: "320mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "11g",
      ),
    ),
    Product(
      id: "youngs_town_sardines",
      name: "Young's Town Sardines in Tomato Sauce",
      brand: "Young's Town",
      variant: "Tomato Sauce",
      category: "Canned Fish",
      imageUrl: "assets/images/youngs_town_sardines.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000005678901",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce", "Salt", "MSG", "Cornstarch"],
      servingInstructions: "Ready to serve. Heat in a pan for 3 minutes before serving.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "75g",
        servingsPerContainer: "2",
        calories: "95 kcal",
        totalFat: "5g",
        saturatedFat: "1.8g",
        transFat: "0g",
        cholesterol: "40mg",
        sodium: "340mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "10g",
      ),
    ),
    Product(
      id: "saba_mackerel_oil",
      name: "Saba Mackerel in Natural Oil",
      brand: "Saba",
      variant: "Natural Oil",
      category: "Canned Fish",
      imageUrl: "assets/images/saba_mackerel.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000006789012",
      allergens: ["Fish (Mackerel)", "Soy"],
      ingredients: ["Mackerel", "Water", "Soybean Oil", "Salt", "MSG"],
      servingInstructions: "Excellent for cooking mackerel soup with ginger, vinegar, and chili leaves.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "80g",
        servingsPerContainer: "2.5",
        calories: "150 kcal",
        totalFat: "11g",
        saturatedFat: "2.5g",
        transFat: "0g",
        cholesterol: "45mg",
        sodium: "280mg",
        totalCarbohydrate: "0g",
        dietaryFiber: "0g",
        sugars: "0g",
        protein: "13g",
      ),
    ),
    Product(
      id: "saba_sardines_tomato",
      name: "Saba Sardines in Tomato Sauce",
      brand: "Saba",
      variant: "Tomato Sauce",
      category: "Canned Fish",
      imageUrl: "assets/images/saba_sardines.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000006789013",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce", "Salt", "Spices", "MSG"],
      servingInstructions: "Ready to eat. Sauté with onion, garlic, and add a dash of calamansi juice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "75g",
        servingsPerContainer: "2",
        calories: "90 kcal",
        totalFat: "4.5g",
        saturatedFat: "1.5g",
        transFat: "0g",
        cholesterol: "38mg",
        sodium: "310mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "10g",
      ),
    ),
    Product(
      id: "rose_bowl_sardines",
      name: "Rose Bowl Gold Sardines in Tomato Sauce",
      brand: "Rose Bowl",
      variant: "Gold Tomato Sauce",
      category: "Canned Fish",
      imageUrl: "assets/images/rose_bowl_sardines.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000007890123",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce (Tomato Paste, Water)", "Salt", "Spices"],
      servingInstructions: "Premium sardines. Sauté with chopped ginger, garlic, and spring onions.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "85g",
        servingsPerContainer: "2",
        calories: "100 kcal",
        totalFat: "5g",
        saturatedFat: "1.8g",
        transFat: "0g",
        cholesterol: "42mg",
        sodium: "300mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0.5g",
        sugars: "1g",
        protein: "12g",
      ),
    ),
    Product(
      id: "san_marino_corned_tuna",
      name: "San Marino Corned Tuna",
      brand: "San Marino",
      variant: "Corned Tuna Original",
      category: "Canned Fish",
      imageUrl: "assets/images/san_marino_tuna.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000008901234",
      allergens: ["Fish (Tuna)", "Soy", "Wheat"],
      ingredients: ["Tuna Flakes", "Water", "Soybean Oil", "Soy Protein", "Salt", "Spices", "MSG", "Onion Powder"],
      servingInstructions: "Sauté with plenty of chopped onions. Perfect quick morning meal with pandesal.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "56g",
        servingsPerContainer: "3",
        calories: "110 kcal",
        totalFat: "7g",
        saturatedFat: "1.5g",
        transFat: "0g",
        cholesterol: "12mg",
        sodium: "280mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0.5g",
        sugars: "0.5g",
        protein: "9g",
      ),
    ),

    // -------------------------------------------------------------
    // CATEGORY: Canned Meats (16-30)
    // -------------------------------------------------------------
    Product(
      id: "purefoods_corned_beef",
      name: "Purefoods Corned Beef Original",
      brand: "Purefoods",
      variant: "Original",
      category: "Canned Meat",
      imageUrl: "assets/images/purefoods_corned_beef.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000009012345",
      allergens: ["Soy"],
      ingredients: ["Cooked Beef", "Beef Broth", "Soy Protein", "Iodized Salt", "Sugar", "Spices", "Monosodium Glutamate", "Sodium Nitrite (Preservative)"],
      servingInstructions: "Sauté with minced garlic, onions, and diced potatoes. Cook until slightly crispy.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "100 kcal",
        totalFat: "7g",
        saturatedFat: "3.5g",
        transFat: "0g",
        cholesterol: "25mg",
        sodium: "340mg",
        totalCarbohydrate: "1g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "8g",
      ),
    ),
    Product(
      id: "purefoods_corned_beef_chili",
      name: "Purefoods Corned Beef Chili Garlic",
      brand: "Purefoods",
      variant: "Chili Garlic",
      category: "Canned Meat",
      imageUrl: "assets/images/purefoods_corned_beef_chili.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000009012346",
      allergens: ["Soy"],
      ingredients: ["Cooked Beef", "Beef Broth", "Chili Pepper", "Garlic Powder", "Soy Protein", "Salt", "Spices", "Sodium Nitrite"],
      servingInstructions: "Sauté with sliced onions and serve with garlic fried rice (sinangag).",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "105 kcal",
        totalFat: "7.5g",
        saturatedFat: "3.8g",
        transFat: "0g",
        cholesterol: "25mg",
        sodium: "350mg",
        totalCarbohydrate: "1g",
        dietaryFiber: "0.2g",
        sugars: "0.5g",
        protein: "8g",
      ),
    ),
    Product(
      id: "cdo_karne_norte_classic",
      name: "CDO Karne Norte Classic",
      brand: "CDO",
      variant: "Karne Norte Classic",
      category: "Canned Meat",
      imageUrl: "assets/images/cdo_karne_norte.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000010123456",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Beef and Poultry Meat", "Water", "Soy Protein", "Wheat Flour", "Iodized Salt", "Sugar", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Heat in a skillet with garlic and red onion. Great for stuffing pandesal or as a rice topping.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "80 kcal",
        totalFat: "4.5g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "15mg",
        sodium: "310mg",
        totalCarbohydrate: "3g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "7g",
      ),
    ),
    Product(
      id: "cdo_karne_norte_chunky",
      name: "CDO Karne Norte Chunky",
      brand: "CDO",
      variant: "Karne Norte Chunky",
      category: "Canned Meat",
      imageUrl: "assets/images/cdo_karne_norte_chunky.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000010123457",
      allergens: ["Soy"],
      ingredients: ["Beef", "Water", "Soy Protein", "Salt", "Sugar", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Sauté with onions, potatoes, and native chili peppers.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "90 kcal",
        totalFat: "5.5g",
        saturatedFat: "2.5g",
        transFat: "0g",
        cholesterol: "20mg",
        sodium: "330mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "8g",
      ),
    ),
    Product(
      id: "argentina_corned_beef",
      name: "Argentina Corned Beef Original",
      brand: "Argentina",
      variant: "Original Corned Beef",
      category: "Canned Meat",
      imageUrl: "assets/images/argentina_corned_beef.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000011234567",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Beef and Poultry Meat", "Broth", "Soy Protein", "Wheat Flour", "Salt", "Sugar", "Spices", "MSG", "Sodium Erythorbate", "Sodium Nitrite"],
      servingInstructions: "Sauté with lots of onions and chopped potatoes. Best cooked a bit dry.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "85 kcal",
        totalFat: "5g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "18mg",
        sodium: "325mg",
        totalCarbohydrate: "3g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "7g",
      ),
    ),
    Product(
      id: "argentina_beef_loaf",
      name: "Argentina Beef Loaf",
      brand: "Argentina",
      variant: "Classic Beef Loaf",
      category: "Canned Meat",
      imageUrl: "assets/images/argentina_beef_loaf.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000011234568",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Beef and Poultry", "Water", "Soy Protein", "Wheat Flour", "Salt", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Slice and fry in vegetable oil until golden brown. Serve with fried egg and rice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "90 kcal",
        totalFat: "6g",
        saturatedFat: "2.5g",
        transFat: "0g",
        cholesterol: "22mg",
        sodium: "360mg",
        totalCarbohydrate: "3g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "6g",
      ),
    ),
    Product(
      id: "cdo_meat_loaf",
      name: "CDO Meat Loaf",
      brand: "CDO",
      variant: "Classic Meat Loaf",
      category: "Canned Meat",
      imageUrl: "assets/images/cdo_meat_loaf.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000012234567",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Pork, Beef and Poultry", "Water", "Soy Protein", "Wheat Starch", "Iodized Salt", "Sugar", "Spices", "Phosphates", "Sodium Nitrite"],
      servingInstructions: "Slice into half-inch slabs and pan-fry. Best paired with ketchup and garlic rice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "85 kcal",
        totalFat: "5g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "20mg",
        sodium: "340mg",
        totalCarbohydrate: "4g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "6g",
      ),
    ),
    Product(
      id: "spam_less_sodium",
      name: "SPAM Less Sodium",
      brand: "SPAM",
      variant: "Less Sodium",
      category: "Canned Meat",
      imageUrl: "assets/images/spam_less_sodium.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000013234567",
      allergens: [],
      ingredients: ["Pork with Ham", "Water", "Modified Potato Starch", "Salt", "Sugar", "Sodium Nitrite"],
      servingInstructions: "Slice and pan-fry without oil until crispy on both sides. Serve with fried rice or in a sandwich.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "56g",
        servingsPerContainer: "6",
        calories: "160 kcal",
        totalFat: "14g",
        saturatedFat: "5g",
        transFat: "0g",
        cholesterol: "40mg",
        sodium: "580mg",
        totalCarbohydrate: "1g",
        dietaryFiber: "0g",
        sugars: "0g",
        protein: "8g",
      ),
    ),
    Product(
      id: "purefoods_vienna_sausage",
      name: "Purefoods Vienna Sausage",
      brand: "Purefoods",
      variant: "Vienna Sausage Original",
      category: "Canned Meat",
      imageUrl: "assets/images/purefoods_vienna_sausage.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000014234567",
      allergens: ["Soy"],
      ingredients: ["Beef, Pork and Poultry", "Water", "Soy Protein", "Salt", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Ready to eat. Can be pan-fried or chopped up and added to omelets and spaghetti.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "2.8",
        calories: "95 kcal",
        totalFat: "7g",
        saturatedFat: "2.8g",
        transFat: "0g",
        cholesterol: "25mg",
        sodium: "320mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "6g",
      ),
    ),
    Product(
      id: "libby_vienna_sausage",
      name: "Libby's Vienna Sausage",
      brand: "Libby's",
      variant: "Vienna Chicken & Beef",
      category: "Canned Meat",
      imageUrl: "assets/images/libby_vienna_sausage.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000015234567",
      allergens: [],
      ingredients: ["Chicken", "Beef", "Pork", "Water", "Salt", "Spices", "Sodium Erythorbate", "Sodium Nitrite"],
      servingInstructions: "Ready to eat cold. Can also be pan-heated or boiled in its own broth for a hot snack.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "60g (3 sausages)",
        servingsPerContainer: "2.5",
        calories: "130 kcal",
        totalFat: "11g",
        saturatedFat: "3.5g",
        transFat: "0g",
        cholesterol: "45mg",
        sodium: "410mg",
        totalCarbohydrate: "1g",
        dietaryFiber: "0g",
        sugars: "0g",
        protein: "6g",
      ),
    ),
    Product(
      id: "del_monte_sausage",
      name: "Del Monte Vienna Sausage",
      brand: "Del Monte",
      variant: "Vienna Sausage",
      category: "Canned Meat",
      imageUrl: "assets/images/del_monte_sausage.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000016234567",
      allergens: ["Soy"],
      ingredients: ["Pork, Beef and Chicken", "Water", "Soy Protein", "Salt", "Condiments", "Sodium Nitrite"],
      servingInstructions: "Ready to eat. Heat in a pan or microwave. Great as a hot dog replacement in breakfast meals.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "90 kcal",
        totalFat: "6.5g",
        saturatedFat: "2.5g",
        transFat: "0g",
        cholesterol: "20mg",
        sodium: "330mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "6g",
      ),
    ),
    Product(
      id: "holiday_beef_loaf",
      name: "Holiday Beef Loaf",
      brand: "Holiday",
      variant: "Beef Loaf Classic",
      category: "Canned Meat",
      imageUrl: "assets/images/holiday_beef_loaf.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000017234567",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Beef & Poultry", "Water", "Soy Protein", "Wheat Flour", "Iodized Salt", "Sugar", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Slice and pan-fry. Best served alongside eggs and garlic rice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "85 kcal",
        totalFat: "5g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "18mg",
        sodium: "350mg",
        totalCarbohydrate: "4g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "6g",
      ),
    ),
    Product(
      id: "maling_pork",
      name: "MaLing Luncheon Meat (Pork)",
      brand: "MaLing",
      variant: "Pork Luncheon Meat",
      category: "Canned Meat",
      imageUrl: "assets/images/maling_pork.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000018234567",
      allergens: [],
      ingredients: ["Pork", "Water", "Cornstarch", "Salt", "Sugar", "Spices", "Sodium Nitrite"],
      servingInstructions: "Slice into slabs and pan-fry in a light oil. Crisp up the outer layer for best flavor.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "56g",
        servingsPerContainer: "7",
        calories: "170 kcal",
        totalFat: "14g",
        saturatedFat: "5.5g",
        transFat: "0g",
        cholesterol: "38mg",
        sodium: "610mg",
        totalCarbohydrate: "3g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "8g",
      ),
    ),
    Product(
      id: "cdo_beef_loaf",
      name: "CDO Beef Loaf",
      brand: "CDO",
      variant: "Classic Beef Loaf",
      category: "Canned Meat",
      imageUrl: "assets/images/cdo_beef_loaf.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000019234567",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Beef and Chicken", "Water", "Soy Protein", "Wheat Starch", "Salt", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Slice and fry. Serve with fried rice or chopped in scrambled eggs.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "85 kcal",
        totalFat: "5g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "18mg",
        sodium: "340mg",
        totalCarbohydrate: "3g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "6g",
      ),
    ),
    Product(
      id: "argentina_corned_chicken",
      name: "Argentina Corned Chicken",
      brand: "Argentina",
      variant: "Corned Chicken Original",
      category: "Canned Meat",
      imageUrl: "assets/images/argentina_chicken.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000020234567",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Chicken Meat", "Water", "Soy Protein", "Wheat Starch", "Salt", "Sugar", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Sauté with chopped onions and serve over a warm bowl of white rice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "75 kcal",
        totalFat: "4g",
        saturatedFat: "1.5g",
        transFat: "0g",
        cholesterol: "20mg",
        sodium: "305mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "8g",
      ),
    ),

    // -------------------------------------------------------------
    // CATEGORY: Instant Noodles (31-45)
    // -------------------------------------------------------------
    Product(
      id: "lucky_me_canton_original",
      name: "Lucky Me! Pancit Canton Original",
      brand: "Lucky Me!",
      variant: "Pancit Canton Original",
      category: "Instant Noodles",
      imageUrl: "assets/images/canton_original.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000021234567",
      allergens: ["Wheat", "Soy", "Sulfite"],
      ingredients: ["Noodles: Wheat Flour, Vegetable Oil, Iodized Salt, Carbonates. Seasoning: Coconut Oil, Soy Sauce (Wheat, Soybean), Sugar, Salt, Flavor Enhancers (MSG), Spices, Dehydrated Vegetables."],
      servingInstructions: "1. Cook noodles in boiling water for 3 minutes.\n2. Mix seasoning, soy sauce, and oil on a plate.\n3. Drain noodles and mix well with the seasonings. Serve hot.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "80g",
        servingsPerContainer: "1",
        calories: "360 kcal",
        totalFat: "14g",
        saturatedFat: "7g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "920mg",
        totalCarbohydrate: "50g",
        dietaryFiber: "2g",
        sugars: "4g",
        protein: "8g",
      ),
    ),
    Product(
      id: "lucky_me_canton_chilimansi",
      name: "Lucky Me! Pancit Canton Chilimansi",
      brand: "Lucky Me!",
      variant: "Pancit Canton Chilimansi",
      category: "Instant Noodles",
      imageUrl: "assets/images/canton_chilimansi.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000021234568",
      allergens: ["Wheat", "Soy", "Sulfite"],
      ingredients: ["Noodles: Wheat Flour, Oil, Salt. Seasoning: Coconut Oil, Soy Sauce, Sugar, Salt, Flavor Enhancers, Chili Powder, Citrus (Calamansi) Acid, Dehydrated Carrots, Spices."],
      servingInstructions: "1. Boil noodles for 3 minutes.\n2. Drain completely.\n3. Toss with seasonings, oil, and sauce. Serve.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "80g",
        servingsPerContainer: "1",
        calories: "360 kcal",
        totalFat: "15g",
        saturatedFat: "7g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "960mg",
        totalCarbohydrate: "48g",
        dietaryFiber: "2g",
        sugars: "5g",
        protein: "8g",
      ),
    ),
    Product(
      id: "lucky_me_canton_sweet_spicy",
      name: "Lucky Me! Pancit Canton Sweet & Spicy",
      brand: "Lucky Me!",
      variant: "Pancit Canton Sweet & Spicy",
      category: "Instant Noodles",
      imageUrl: "assets/images/canton_sweet_spicy.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000021234569",
      allergens: ["Wheat", "Soy", "Sulfite"],
      ingredients: ["Noodles: Wheat Flour, Oil, Salt. Seasoning: Coconut Oil, Soy Sauce, Sugar, Chili Powder, Spices, Salt, Enhancers."],
      servingInstructions: "1. Cook noodles in boiling water for 3 minutes.\n2. Drain. Mix well with the flavor packet on a plate.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "80g",
        servingsPerContainer: "1",
        calories: "365 kcal",
        totalFat: "14g",
        saturatedFat: "7g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "940mg",
        totalCarbohydrate: "51g",
        dietaryFiber: "2g",
        sugars: "6g",
        protein: "8g",
      ),
    ),
    Product(
      id: "lucky_me_canton_hot_chili",
      name: "Lucky Me! Pancit Canton Extra Hot Chili",
      brand: "Lucky Me!",
      variant: "Pancit Canton Extra Hot Chili",
      category: "Instant Noodles",
      imageUrl: "assets/images/canton_hot_chili.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000021234570",
      allergens: ["Wheat", "Soy", "Sulfite"],
      ingredients: ["Wheat Flour, Oil, Salt, Soy Sauce, Hot Chili Seasoning, Msg, Sugar, Dehydrated Vegetables."],
      servingInstructions: "Boil noodles for 3 minutes, drain thoroughly, mix with dry spices, oil, and soy sauce packs.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "80g",
        servingsPerContainer: "1",
        calories: "365 kcal",
        totalFat: "15g",
        saturatedFat: "7.5g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "980mg",
        totalCarbohydrate: "49g",
        dietaryFiber: "2g",
        sugars: "4g",
        protein: "8g",
      ),
    ),
    Product(
      id: "lucky_me_beef_mami",
      name: "Lucky Me! Instant Noodle Soup Beef Mami",
      brand: "Lucky Me!",
      variant: "Beef Mami",
      category: "Instant Noodles",
      imageUrl: "assets/images/beef_mami.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000022234567",
      allergens: ["Wheat", "Soy", "Celery"],
      ingredients: ["Noodle: Wheat Flour, Oil, Salt. Seasoning: Salt, Sugar, Beef Flavor (Artificial), MSG, Caramel Color, Spices, Dehydrated Chives."],
      servingInstructions: "1. Cook noodles in 2 cups (approx. 400ml) boiling water for 3 minutes.\n2. Remove from heat and stir in seasoning powder. Serve hot.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "55g",
        servingsPerContainer: "1",
        calories: "240 kcal",
        totalFat: "9g",
        saturatedFat: "4.5g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "1050mg",
        totalCarbohydrate: "34g",
        dietaryFiber: "1g",
        sugars: "2g",
        protein: "5g",
      ),
    ),
    Product(
      id: "lucky_me_chicken_mami",
      name: "Lucky Me! Instant Noodle Soup Chicken Mami",
      brand: "Lucky Me!",
      variant: "Chicken Mami",
      category: "Instant Noodles",
      imageUrl: "assets/images/chicken_mami.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000022234568",
      allergens: ["Wheat", "Soy", "Sulfite"],
      ingredients: ["Wheat Flour, Oil, Salt, Chicken Flavoring (Artificial), MSG, Sugar, Onion, Dehydrated Leeks."],
      servingInstructions: "Boil noodles in 400ml water for 3 minutes. Turn off fire, pour seasoning, stir well, and serve.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "55g",
        servingsPerContainer: "1",
        calories: "235 kcal",
        totalFat: "8.5g",
        saturatedFat: "4g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "1020mg",
        totalCarbohydrate: "34g",
        dietaryFiber: "1g",
        sugars: "1g",
        protein: "5g",
      ),
    ),
    Product(
      id: "nissin_yakisoba_spicy_chicken",
      name: "Nissin Yakisoba Spicy Chicken",
      brand: "Nissin",
      variant: "Spicy Chicken Yakisoba",
      category: "Instant Noodles",
      imageUrl: "assets/images/nissin_yakisoba.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000023234567",
      allergens: ["Wheat", "Soy", "Egg"],
      ingredients: ["Wheat Flour, Vegetable Oil, Soy Sauce, Chili Paste, Chicken Powder, Salt, MSG, Dehydrated Vegetables."],
      servingInstructions: "1. Boil noodles in 400ml water for 3 minutes.\n2. Drain water completely.\n3. Add liquid sauce and seasoning. Mix thoroughly.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "59g",
        servingsPerContainer: "1",
        calories: "270 kcal",
        totalFat: "12g",
        saturatedFat: "5g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "790mg",
        totalCarbohydrate: "36g",
        dietaryFiber: "1g",
        sugars: "3g",
        protein: "5g",
      ),
    ),
    Product(
      id: "nissin_ramen_seafood",
      name: "Nissin Ramen Seafood Cup",
      brand: "Nissin",
      variant: "Seafood Cup Noodle",
      category: "Instant Noodles",
      imageUrl: "assets/images/nissin_ramen_seafood.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000023234568",
      allergens: ["Wheat", "Soy", "Fish", "Crustaceans (Shrimp)", "Milk", "Egg"],
      ingredients: ["Wheat Flour, Palm Oil, Salt, Dehydrated Crab Sticks, Dehydrated Egg, Dehydrated Squid, Shrimp Powder, Pork Extract, Whey Powder, Spices, MSG."],
      servingInstructions: "1. Open lid halfway.\n2. Add boiling water up to the inner line.\n3. Close lid and wait for 3 minutes. Stir well and enjoy.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "40g",
        servingsPerContainer: "1",
        calories: "180 kcal",
        totalFat: "8g",
        saturatedFat: "4g",
        transFat: "0g",
        cholesterol: "10mg",
        sodium: "650mg",
        totalCarbohydrate: "24g",
        dietaryFiber: "1g",
        sugars: "1g",
        protein: "4g",
      ),
    ),
    Product(
      id: "nissin_cup_noodles_batchoy",
      name: "Nissin Cup Noodles Batchoy",
      brand: "Nissin",
      variant: "Batchoy Cup Noodle",
      category: "Instant Noodles",
      imageUrl: "assets/images/nissin_batchoy.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000023234569",
      allergens: ["Wheat", "Soy", "Sulfite"],
      ingredients: ["Noodles: Wheat Flour, Vegetable Oil, Iodized Salt, Carbonates. Soup Base: Iodized Salt, Chicken Flavor, Garlic Oil, MSG, Onion, Dehydrated Chives, Spices."],
      servingInstructions: "1. Open lid halfway.\n2. Add boiling water up to the inner line.\n3. Close lid and wait for 3 minutes. Stir well and enjoy.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "60g",
        servingsPerContainer: "1",
        calories: "280 kcal",
        totalFat: "11g",
        saturatedFat: "3g",
        transFat: "0g",
        cholesterol: "5mg",
        sodium: "1250mg",
        totalCarbohydrate: "40g",
        dietaryFiber: "1g",
        sugars: "4g",
        protein: "18g",
      ),
    ),
    Product(
      id: "payless_canton_xtra_big_chilimansi",
      name: "Payless Instant Pancit Canton Xtra Big Chilimansi",
      brand: "Payless",
      variant: "Xtra Big Chilimansi",
      category: "Instant Noodles",
      imageUrl: "assets/images/payless_chilimansi.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000024234567",
      allergens: ["Wheat", "Soy"],
      ingredients: ["Noodle: Wheat Flour, Oil, Salt. Seasoning: Iodized Salt, Sugar, MSG, Soy Sauce, Calamansi Powder, Spices, Vegetable Oil."],
      servingInstructions: "1. Boil the big noodle block in 3 cups of water for 3 minutes.\n2. Drain water.\n3. Combine noodle with seasoning powder, oil, and sauce. Mix well.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "130g",
        servingsPerContainer: "1",
        calories: "590 kcal",
        totalFat: "24g",
        saturatedFat: "12g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "1550mg",
        totalCarbohydrate: "82g",
        dietaryFiber: "3g",
        sugars: "8g",
        protein: "12g",
      ),
    ),
    Product(
      id: "payless_canton_xtra_big_sweet_spicy",
      name: "Payless Instant Pancit Canton Xtra Big Sweet & Spicy",
      brand: "Payless",
      variant: "Xtra Big Sweet & Spicy",
      category: "Instant Noodles",
      imageUrl: "assets/images/payless_sweet_spicy.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000024234568",
      allergens: ["Wheat", "Soy"],
      ingredients: ["Wheat Flour, Vegetable Oil, Sugar, Soy Sauce, Salt, MSG, Chili Flakes, Spices."],
      servingInstructions: "Boil noodles for 3 minutes, drain water, mix seasoning packets on a plate, add noodles, toss together.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "130g",
        servingsPerContainer: "1",
        calories: "600 kcal",
        totalFat: "25g",
        saturatedFat: "12g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "1510mg",
        totalCarbohydrate: "83g",
        dietaryFiber: "3g",
        sugars: "9g",
        protein: "12g",
      ),
    ),
    Product(
      id: "lucky_me_lomi",
      name: "Lucky Me! Instant Noodle Lomi",
      brand: "Lucky Me!",
      variant: "Lomi Egg Noodle Soup",
      category: "Instant Noodles",
      imageUrl: "assets/images/lomi.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000025234567",
      allergens: ["Wheat", "Egg", "Soy"],
      ingredients: ["Wheat Flour, Vegetable Oil, Starch, Egg Powder, Iodized Salt, Chicken Flavor, Dehydrated Chives, Spices, MSG."],
      servingInstructions: "Boil in 450ml water for 4 minutes. Stir in the soup powder and starch mix to create a thick, authentic egg soup texture.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "60g",
        servingsPerContainer: "1",
        calories: "260 kcal",
        totalFat: "10g",
        saturatedFat: "5g",
        transFat: "0g",
        cholesterol: "15mg",
        sodium: "1180mg",
        totalCarbohydrate: "36g",
        dietaryFiber: "1g",
        sugars: "2g",
        protein: "6g",
      ),
    ),
    Product(
      id: "lucky_me_bulalo",
      name: "Lucky Me! Supreme Bulalo Cup",
      brand: "Lucky Me!",
      variant: "Supreme Bulalo Noodle Soup",
      category: "Instant Noodles",
      imageUrl: "assets/images/bulalo_cup.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000025234568",
      allergens: ["Wheat", "Soy", "Sulfite"],
      ingredients: ["Wheat Flour, Vegetable Oil, Bulalo Flavor (Beef Shank Extract, Artificial Bone Marrow), Cabbage, Salt, Spices, MSG, Natural Color."],
      servingInstructions: "Open cup lid, add seasoning, pour boiling water up to line, cover for 3 minutes, stir well.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "70g",
        servingsPerContainer: "1",
        calories: "310 kcal",
        totalFat: "12g",
        saturatedFat: "6g",
        transFat: "0g",
        cholesterol: "2mg",
        sodium: "1350mg",
        totalCarbohydrate: "44g",
        dietaryFiber: "1.5g",
        sugars: "2g",
        protein: "7g",
      ),
    ),
    Product(
      id: "quickchow_mami_beef",
      name: "Quickchow Instant Noodle Beef Mami",
      brand: "Quickchow",
      variant: "Beef Mami",
      category: "Instant Noodles",
      imageUrl: "assets/images/quickchow_beef.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000026234567",
      allergens: ["Wheat", "Soy"],
      ingredients: ["Wheat Flour, Vegetable Oil, Iodized Salt, Beef Seasoning, MSG, Spices, Sugar, Caramel Color."],
      servingInstructions: "Cook in 2 cups of boiling water for 3 minutes. Stir in flavor pack and serve hot.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "55g",
        servingsPerContainer: "1",
        calories: "230 kcal",
        totalFat: "8.5g",
        saturatedFat: "4g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "1010mg",
        totalCarbohydrate: "33g",
        dietaryFiber: "1g",
        sugars: "1g",
        protein: "5g",
      ),
    ),
    Product(
      id: "lucky_me_go_cup_hot_chili",
      name: "Lucky Me! Go Cup Extra Hot Chili",
      brand: "Lucky Me!",
      variant: "Go Cup Extra Hot Chili",
      category: "Instant Noodles",
      imageUrl: "assets/images/gocup_spicy.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000027234567",
      allergens: ["Wheat", "Soy"],
      ingredients: ["Wheat Flour, Vegetable Oil, Chili Pepper, Soy Sauce, Salt, MSG, Dehydrated Carrots, Spices."],
      servingInstructions: "Pour hot water inside, close lid, wait for 3 minutes, mix, and eat.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "40g",
        servingsPerContainer: "1",
        calories: "175 kcal",
        totalFat: "7g",
        saturatedFat: "3.5g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "720mg",
        totalCarbohydrate: "24g",
        dietaryFiber: "0.5g",
        sugars: "1g",
        protein: "4g",
      ),
    ),
    Product(
      id: "lucky_me_sotanghon",
      name: "Lucky Me! Supreme Sotanghon Cup",
      brand: "Lucky Me!",
      variant: "Supreme Sotanghon Soup",
      category: "Instant Noodles",
      imageUrl: "assets/images/sotanghon.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000027234568",
      allergens: ["Soy", "Sulfite"],
      ingredients: ["Sotanghon Noodles: Potato and Mung Bean Starch. Soup Base: Iodized Salt, Chicken Flavor, Garlic Oil, MSG, Onion, Dehydrated Chives, Spices."],
      servingInstructions: "Open cup, add garlic oil and powder seasoning. Add boiling water, cover for 3 minutes, mix and serve.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "45g",
        servingsPerContainer: "1",
        calories: "160 kcal",
        totalFat: "3.5g",
        saturatedFat: "1g",
        transFat: "0g",
        cholesterol: "0mg",
        sodium: "810mg",
        totalCarbohydrate: "31g",
        dietaryFiber: "0.5g",
        sugars: "1g",
        protein: "1g",
      ),
    ),

    // -------------------------------------------------------------
    // ADDITIONAL FILIPINO SKUS (41-45 for Canned Fish / Meat)
    // -------------------------------------------------------------
    Product(
      id: "cdo_corned_beef_classic",
      name: "CDO Corned Beef Classic",
      brand: "CDO",
      variant: "Classic Corned Beef",
      category: "Canned Meat",
      imageUrl: "assets/images/cdo_corned_beef.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000028234567",
      allergens: ["Soy"],
      ingredients: ["Beef", "Water", "Soy Protein", "Salt", "Sugar", "Spices", "MSG", "Sodium Nitrite"],
      servingInstructions: "Sauté in minced garlic and onions. Great with a side of toasted bread.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "85 kcal",
        totalFat: "5g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "18mg",
        sodium: "320mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "0.5g",
        protein: "8g",
      ),
    ),
    Product(
      id: "el_rey_sardines_tomato",
      name: "El Rey Sardines in Tomato Sauce",
      brand: "El Rey",
      variant: "Tomato Sauce",
      category: "Canned Fish",
      imageUrl: "assets/images/el_rey_sardines.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000029234567",
      allergens: ["Fish (Sardines)"],
      ingredients: ["Sardines", "Tomato Sauce", "Salt", "Modified Starch", "Spices"],
      servingInstructions: "Heat in a saucepan and serve hot with chopped yellow onions.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "75g",
        servingsPerContainer: "2",
        calories: "90 kcal",
        totalFat: "4.5g",
        saturatedFat: "1.5g",
        transFat: "0g",
        cholesterol: "38mg",
        sodium: "315mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1g",
        protein: "10g",
      ),
    ),
    Product(
      id: "argentina_sisig_canned",
      name: "Argentina Sisig Canned",
      brand: "Argentina",
      variant: "Pork Sisig Classic",
      category: "Canned Meat",
      imageUrl: "assets/images/argentina_sisig.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000030234567",
      allergens: ["Soy", "Wheat"],
      ingredients: ["Pork Meat and Offal", "Water", "Soy Protein", "Vinegar", "Onions", "Chili Pepper", "Wheat Flour", "Salt", "Spices", "MSG"],
      servingInstructions: "Sauté in a very hot pan until edges are crispy. Squeeze fresh calamansi and add a red onion garnish before serving.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "50g",
        servingsPerContainer: "3",
        calories: "110 kcal",
        totalFat: "8g",
        saturatedFat: "3g",
        transFat: "0g",
        cholesterol: "25mg",
        sodium: "370mg",
        totalCarbohydrate: "3g",
        dietaryFiber: "0.2g",
        sugars: "0.5g",
        protein: "6g",
      ),
    ),
    Product(
      id: "555_sardines_caldereta",
      name: "555 Sardines Caldereta Style",
      brand: "555",
      variant: "Caldereta Style",
      category: "Canned Fish",
      imageUrl: "assets/images/555_caldereta.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000031234567",
      allergens: ["Fish (Sardines)", "Soy", "Wheat"],
      ingredients: ["Sardines", "Water", "Tomato Paste", "Soybean Oil", "Sugar", "Cheese Powder", "Bell Pepper", "Salt", "Spices", "Monosodium Glutamate"],
      servingInstructions: "Heat in a skillet. Excellent with bell peppers, green peas, and hot rice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "75g",
        servingsPerContainer: "2",
        calories: "105 kcal",
        totalFat: "6g",
        saturatedFat: "2g",
        transFat: "0g",
        cholesterol: "35mg",
        sodium: "330mg",
        totalCarbohydrate: "3g",
        dietaryFiber: "0.5g",
        sugars: "2g",
        protein: "9g",
      ),
    ),
    Product(
      id: "century_tuna_adobo",
      name: "Century Tuna Flakes adobo Style",
      brand: "Century Tuna",
      variant: "Adobo Style",
      category: "Canned Fish",
      imageUrl: "assets/images/century_tuna_adobo.png",
      fdaStatus: "Registered",
      fdaRegistrationNumber: "FR-4000032234567",
      allergens: ["Fish (Tuna)", "Soy", "Wheat"],
      ingredients: ["Tuna Flakes", "Water", "Soy Sauce", "Soybean Oil", "Sugar", "Vinegar", "Garlic Powder", "Spices", "MSG"],
      servingInstructions: "Sauté with fried garlic bits and white onions. Best served hot over warm white rice.",
      nutritionalFacts: NutritionalFacts(
        servingSize: "56g",
        servingsPerContainer: "3",
        calories: "125 kcal",
        totalFat: "8g",
        saturatedFat: "1.4g",
        transFat: "0g",
        cholesterol: "15mg",
        sodium: "310mg",
        totalCarbohydrate: "2g",
        dietaryFiber: "0g",
        sugars: "1.5g",
        protein: "10g",
      ),
    ),
  ];

  Product? getProductById(String id) {
    try {
      return _products.firstWhere((p) => p.id == id);
    } catch (_) {
      return null;
    }
  }

  List<Product> getAllProducts() {
    return _products;
  }

  List<Product> searchProducts(String query) {
    if (query.isEmpty) return [];
    final q = query.toLowerCase();
    return _products.where((p) =>
      p.name.toLowerCase().contains(q) ||
      p.brand.toLowerCase().contains(q) ||
      p.variant.toLowerCase().contains(q) ||
      p.category.toLowerCase().contains(q)
    ).toList();
  }

  // Returns 1 to 3 random mock products with bounding boxes for scan simulation.
  List<Product> getRandomMockProducts(int count) {
    final list = List<Product>.from(_products)..shuffle();
    return list.take(count.clamp(1, _products.length)).toList();
  }

  /// Returns all products in the same category as [category].
  /// The [excludeId] product is placed at the bottom so similar products
  /// come first in the comparison list.
  List<Product> getProductsByCategory(String category,
      {String? excludeId}) {
    final matches = _products
        .where((p) => p.category == category)
        .toList();

    if (excludeId != null) {
      // Move the current product to the end so similar ones appear first
      matches.sort((a, b) {
        if (a.id == excludeId) return 1;
        if (b.id == excludeId) return -1;
        return 0;
      });
    }
    return matches;
  }

  /// Returns all distinct categories in the database.
  List<String> getCategories() {
    return _products.map((p) => p.category).toSet().toList()..sort();
  }
}
