// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Uv5V78zCqi66yTjj3a5DUNsKRRnj1qk',
    appId: '1:1033502181973:web:91e1da13e5cdfb01ff22dc',
    messagingSenderId: '1033502181973',
    projectId: 'claro-e90dd',
    authDomain: 'claro-e90dd.firebaseapp.com',
    storageBucket: 'claro-e90dd.firebasestorage.app',
    measurementId: 'G-WLX4JJSPFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9zyM5qv29DtCmeRXoE4hcqA1Y5nehSy8',
    appId: '1:1033502181973:android:950155c1c720b622ff22dc',
    messagingSenderId: '1033502181973',
    projectId: 'claro-e90dd',
    storageBucket: 'claro-e90dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrA5ZB6VO36dFHSJqkBNAlutkJPnVevg',
    appId: '1:1033502181973:ios:4f56c0973fdc8e99ff22dc',
    messagingSenderId: '1033502181973',
    projectId: 'claro-e90dd',
    storageBucket: 'claro-e90dd.firebasestorage.app',
    androidClientId: '1033502181973-8a3pl7iom0hlmihlgof4juohc54vnpq8.apps.googleusercontent.com',
    iosClientId: '1033502181973-1b0hi1gbam9jkln28jvpsiderigjmhe9.apps.googleusercontent.com',
    iosBundleId: 'com.example.claro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrA5ZB6VO36dFHSJqkBNAlutkJPnVevg',
    appId: '1:1033502181973:ios:4f56c0973fdc8e99ff22dc',
    messagingSenderId: '1033502181973',
    projectId: 'claro-e90dd',
    storageBucket: 'claro-e90dd.firebasestorage.app',
    androidClientId: '1033502181973-8a3pl7iom0hlmihlgof4juohc54vnpq8.apps.googleusercontent.com',
    iosClientId: '1033502181973-1b0hi1gbam9jkln28jvpsiderigjmhe9.apps.googleusercontent.com',
    iosBundleId: 'com.example.claro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Uv5V78zCqi66yTjj3a5DUNsKRRnj1qk',
    appId: '1:1033502181973:web:a9e985ac427661b0ff22dc',
    messagingSenderId: '1033502181973',
    projectId: 'claro-e90dd',
    authDomain: 'claro-e90dd.firebaseapp.com',
    storageBucket: 'claro-e90dd.firebasestorage.app',
    measurementId: 'G-ZXEGCWQT7E',
  );
}
