import 'package:flutter/material.dart';
import '../generated/l10n/app_localizations.dart';

/// One block of body content within a [_TermsSection]. Either a plain
/// paragraph ([paragraph] set) or a bulleted list ([bullets] set).
class _TermsBlock {
  final String? paragraph;
  final List<String>? bullets;

  const _TermsBlock.paragraph(this.paragraph) : bullets = null;
  const _TermsBlock.bullets(this.bullets) : paragraph = null;
}

class _TermsSection {
  final String title;
  final List<_TermsBlock> blocks;

  const _TermsSection(this.title, this.blocks);
}

/// Full text of CLARO's Terms & Conditions, reproduced verbatim from the
/// source document and broken into sections/bullets purely for on-screen
/// readability. No content is omitted or truncated.
const _termsLastUpdated = 'Last Updated: August 10, 2026';
const _termsVersion = 'Terms Version 1.0';
const _termsIntro =
    'These Terms and Conditions ("Terms") govern your access to and use of '
    'the CLARO mobile application and its related services. By creating an '
    'account or using CLARO, you agree to these Terms. If you do not agree '
    'with these Terms, please do not use the application.';

final List<_TermsSection> _termsSections = [
  _TermsSection('1. About CLARO', [
    const _TermsBlock.paragraph(
      'CLARO is a food product recognition and nutritional information '
      'application designed to help users identify selected food products '
      'and understand information such as:',
    ),
    const _TermsBlock.bullets([
      'Product information',
      'Nutritional values',
      'FDA registration information',
      'Nutri-Score',
      'NOVA classification',
      'Allergen information',
      'Health-related advisories',
      'Product comparisons and rankings',
    ]),
    const _TermsBlock.paragraph(
      "The application may also provide personalized recommendations "
      "based on information voluntarily entered into the user's health "
      "profile.",
    ),
  ]),
  _TermsSection('2. Eligibility and Account', [
    const _TermsBlock.paragraph(
      'To access features requiring authentication, you must create or '
      'access a CLARO account using one of the authentication methods '
      'supported by the application.',
    ),
    const _TermsBlock.paragraph('You are responsible for:'),
    const _TermsBlock.bullets([
      'Providing accurate information when required',
      'Maintaining the security of your account',
      'Keeping your authentication credentials confidential',
      'Not sharing your account with unauthorized individuals',
      'Immediately reporting suspected unauthorized access',
    ]),
    const _TermsBlock.paragraph(
      'CLARO may restrict or terminate access when an account is used in '
      'violation of these Terms or in a manner that threatens the security '
      'or integrity of the system.',
    ),
  ]),
  _TermsSection('3. Health Profile', [
    const _TermsBlock.paragraph(
      'CLARO allows users to provide information about their health '
      'conditions and food allergies.',
    ),
    const _TermsBlock.paragraph(
      'This information is used to personalize product advisories, '
      'warnings, and recommendations.',
    ),
    const _TermsBlock.paragraph(
      'You are responsible for ensuring that the information in your '
      'health profile is accurate and up to date.',
    ),
    const _TermsBlock.paragraph(
      'If your health information changes, you should update your profile '
      'accordingly.',
    ),
  ]),
  _TermsSection('4. Health and Medical Disclaimer', [
    const _TermsBlock.paragraph(
      'CLARO is an informational and educational tool and is not a '
      'substitute for professional medical advice, diagnosis, or '
      'treatment.',
    ),
    const _TermsBlock.paragraph(
      'Health advisories, warnings, classifications, and recommendations '
      'generated by CLARO are intended to help users understand '
      'nutritional and product-related information.',
    ),
    const _TermsBlock.paragraph('They should not be interpreted as:'),
    const _TermsBlock.bullets([
      'A medical diagnosis',
      'A prescription',
      'A treatment plan',
      'Professional dietary advice',
      'A substitute for consultation with a physician, registered '
          'dietitian, nutritionist, or other qualified healthcare '
          'professional',
    ]),
    const _TermsBlock.paragraph(
      'Users with medical conditions, food allergies, dietary '
      'restrictions, or other health concerns should consult an '
      'appropriate healthcare professional before making significant '
      'dietary or health-related decisions.',
    ),
    const _TermsBlock.paragraph(
      'In case of an allergic reaction or medical emergency, seek '
      'appropriate professional medical assistance immediately.',
    ),
  ]),
  _TermsSection('5. Accuracy of Information', [
    const _TermsBlock.paragraph(
      'CLARO attempts to provide useful and relevant product and '
      'nutritional information. However, information may originate from '
      'databases, publicly available sources, product labels, OCR '
      'extraction, or other reference sources.',
    ),
    const _TermsBlock.paragraph(
      'Accordingly, CLARO does not guarantee that all information will '
      'always be:',
    ),
    const _TermsBlock.bullets([
      'Accurate',
      'Complete',
      'Current',
      'Error-free',
      'Available',
      "Suitable for a particular individual's circumstances",
    ]),
    const _TermsBlock.paragraph(
      "Users should verify important nutritional, allergen, and "
      "regulatory information using the product's official packaging, "
      "labeling, or appropriate authoritative sources.",
    ),
  ]),
  _TermsSection('6. Product Recognition', [
    const _TermsBlock.paragraph(
      'CLARO uses image recognition technology to identify supported food '
      'products.',
    ),
    const _TermsBlock.paragraph(
      'Recognition results may occasionally be incorrect because of:',
    ),
    const _TermsBlock.bullets([
      'Image quality',
      'Lighting conditions',
      'Camera positioning',
      'Product packaging changes',
      'Similar product designs',
      'Occlusion or obstruction',
      'Model limitations',
    ]),
    const _TermsBlock.paragraph(
      'Users should verify the identified product before relying on the '
      'information presented by the application.',
    ),
  ]),
  _TermsSection('7. Product Comparison and Ranking', [
    const _TermsBlock.paragraph(
      'CLARO may provide product comparisons and rankings based on '
      "nutritional information and, where applicable, the user's health "
      'profile.',
    ),
    const _TermsBlock.paragraph(
      'These rankings are intended to assist users in comparing products.',
    ),
    const _TermsBlock.paragraph(
      'A higher-ranked product does not necessarily mean that it is '
      'medically or nutritionally appropriate for every individual.',
    ),
    const _TermsBlock.paragraph(
      'Users should consider their personal circumstances and consult '
      'qualified professionals when necessary.',
    ),
  ]),
  _TermsSection('8. Nutri-Score and NOVA Classification', [
    const _TermsBlock.paragraph(
      'CLARO may display Nutri-Score and NOVA classifications to help '
      'users understand nutritional quality and processing levels.',
    ),
    const _TermsBlock.paragraph(
      'These classifications are provided for informational purposes.',
    ),
    const _TermsBlock.paragraph(
      "They should not be interpreted as a complete assessment of a "
      "product's overall healthfulness or suitability for a particular "
      "individual.",
    ),
  ]),
  _TermsSection('9. FDA and Regulatory Information', [
    const _TermsBlock.paragraph(
      'CLARO may display Philippine FDA-related information, including '
      'product registration numbers and validity dates, as reference '
      'information.',
    ),
    const _TermsBlock.paragraph(
      'The application does not independently issue, modify, or grant FDA '
      'registration.',
    ),
    const _TermsBlock.paragraph(
      'Regulatory information displayed by CLARO should be verified '
      'through appropriate official Philippine FDA sources when '
      'regulatory confirmation is required.',
    ),
  ]),
  _TermsSection('10. Voice Assistant', [
    const _TermsBlock.paragraph(
      'CLARO may provide voice-assisted navigation and interaction.',
    ),
    const _TermsBlock.paragraph(
      'Users are responsible for ensuring that microphone permissions are '
      'appropriately configured on their device.',
    ),
    const _TermsBlock.paragraph(
      'Voice recognition may not always accurately understand spoken '
      'commands because of factors such as:',
    ),
    const _TermsBlock.bullets([
      'Background noise',
      'Pronunciation',
      'Accent',
      'Microphone quality',
      'Internet connectivity',
      'Language selection',
    ]),
    const _TermsBlock.paragraph(
      'Users should not rely exclusively on voice commands for critical '
      'actions.',
    ),
  ]),
  _TermsSection('11. User-Submitted Product Reports', [
    const _TermsBlock.paragraph(
      'Users may submit reports for products that CLARO does not '
      'recognize.',
    ),
    const _TermsBlock.paragraph(
      'Users agree that submitted information should be:',
    ),
    const _TermsBlock.bullets([
      'Accurate to the best of their knowledge',
      'Relevant to the product being reported',
      'Free from intentionally misleading information',
      "Appropriate for the application's intended purpose",
    ]),
    const _TermsBlock.paragraph(
      'CLARO administrators may review, validate, reject, or otherwise '
      'process submitted reports.',
    ),
    const _TermsBlock.paragraph(
      "Submitting a report does not guarantee that the product will be "
      "added to the application's database.",
    ),
  ]),
  _TermsSection('12. Prohibited Use', [
    const _TermsBlock.paragraph('You agree not to use CLARO to:'),
    const _TermsBlock.bullets([
      'Provide intentionally false or misleading information',
      'Submit fraudulent product reports',
      "Attempt to access another user's account",
      "Attempt to access another user's health information",
      'Circumvent authentication or security controls',
      "Interfere with the application's operation",
      'Abuse or overload application services',
      'Reverse engineer or attempt to compromise security mechanisms',
      'Use the application for unlawful purposes',
      "Use another person's personal information without authorization",
    ]),
    const _TermsBlock.paragraph(
      "CLARO reserves the right to restrict access where misuse threatens "
      "the application's users, data, or infrastructure.",
    ),
  ]),
  _TermsSection('13. Intellectual Property', [
    const _TermsBlock.paragraph(
      'The CLARO application, including its software, interface, design, '
      'branding, logos, original written content, and other original '
      'materials, is owned by or licensed to the CLARO development team '
      'and is protected by applicable intellectual property laws.',
    ),
    const _TermsBlock.paragraph(
      "Unless expressly permitted, users may not reproduce, redistribute, "
      "modify, or commercially exploit CLARO's original materials without "
      "appropriate authorization.",
    ),
    const _TermsBlock.paragraph(
      'Third-party names, trademarks, databases, and services remain the '
      'property of their respective owners.',
    ),
  ]),
  _TermsSection('14. Third-Party Services', [
    const _TermsBlock.paragraph(
      'CLARO may rely on third-party services such as:',
    ),
    const _TermsBlock.bullets([
      'Firebase Authentication',
      'Firebase Firestore',
      'Google OAuth',
      'Nutritional and regulatory reference databases',
      'AI services used for advisory explanations',
    ]),
    const _TermsBlock.paragraph(
      "The availability and operation of these third-party services may "
      "affect CLARO's functionality.",
    ),
    const _TermsBlock.paragraph(
      'Third-party services may have their own terms, privacy policies, '
      'and technical limitations.',
    ),
  ]),
  _TermsSection('15. Availability of the Application', [
    const _TermsBlock.paragraph(
      'We aim to keep CLARO available and functional; however, '
      'uninterrupted availability cannot be guaranteed.',
    ),
    const _TermsBlock.paragraph(
      'The application may temporarily become unavailable because of:',
    ),
    const _TermsBlock.bullets([
      'Maintenance',
      'Software updates',
      'Server or cloud-service interruptions',
      'Internet connectivity issues',
      'Third-party service outages',
      'Security incidents',
      'Technical failures',
    ]),
    const _TermsBlock.paragraph(
      'CLARO may modify, suspend, or discontinue certain features when '
      'necessary.',
    ),
  ]),
  _TermsSection('16. Account Deletion', [
    const _TermsBlock.paragraph(
      "Users may request deletion of their CLARO account through the "
      "application's account deletion feature.",
    ),
    const _TermsBlock.paragraph(
      'Once successfully processed, the account and associated user '
      "information will be deleted in accordance with the application's "
      'Privacy Policy and applicable requirements.',
    ),
    const _TermsBlock.paragraph(
      'Account deletion may result in permanent loss of access to '
      'information associated with the account.',
    ),
  ]),
  _TermsSection('17. Disclaimer of Warranties', [
    const _TermsBlock.paragraph(
      'To the extent permitted by applicable law, CLARO is provided on an '
      '"as is" and "as available" basis.',
    ),
    const _TermsBlock.paragraph('We do not guarantee that:'),
    const _TermsBlock.bullets([
      'The application will always be available',
      'Product recognition will always be accurate',
      'Nutritional information will always be complete or current',
      'Health recommendations will be appropriate for every user',
      'Third-party services will always be available',
      'The application will be free from all errors or interruptions',
    ]),
  ]),
  _TermsSection('18. Limitation of Liability', [
    const _TermsBlock.paragraph(
      'To the extent permitted by applicable law, CLARO and its '
      'development team shall not be responsible for losses or damages '
      'resulting from reliance on information provided by the '
      'application, including nutritional information, product '
      'classifications, product rankings, health advisories, or product '
      'recognition results.',
    ),
    const _TermsBlock.paragraph(
      'Users remain responsible for verifying information and making '
      'their own decisions regarding food consumption and health.',
    ),
    const _TermsBlock.paragraph(
      'Nothing in these Terms is intended to exclude or limit rights or '
      'obligations that cannot legally be excluded or limited under '
      'applicable law.',
    ),
  ]),
  _TermsSection('19. Privacy', [
    const _TermsBlock.paragraph(
      'Your use of CLARO is also governed by our Privacy Policy, which '
      'explains how personal information is collected, used, stored, '
      'protected, and managed.',
    ),
    const _TermsBlock.paragraph(
      'By using CLARO, you acknowledge that you have reviewed the Privacy '
      'Policy.',
    ),
  ]),
  _TermsSection('20. Changes to These Terms', [
    const _TermsBlock.paragraph(
      'We may update these Terms when necessary to reflect changes to the '
      'application, its features, or applicable requirements.',
    ),
    const _TermsBlock.paragraph(
      'Updated Terms will be posted on this page with a revised Last '
      'Updated date.',
    ),
    const _TermsBlock.paragraph(
      'Your continued use of CLARO after changes are posted constitutes '
      'acceptance of the updated Terms, to the extent permitted by '
      'applicable law.',
    ),
  ]),
  _TermsSection('21. Governing Law', [
    const _TermsBlock.paragraph(
      'These Terms shall be interpreted and governed in accordance with '
      'the applicable laws of the Republic of the Philippines, including '
      'relevant provisions applicable to the use of digital services and '
      'data protection.',
    ),
  ]),
];

/// Shows the Terms & Conditions in a modal card with a fixed width/height,
/// a header (title + close button) that stays put, and only the body text
/// scrolling underneath it. Follows the app's existing theme (light/dark)
/// via [Theme.of], so it renders correctly regardless of which mode is
/// active in the surrounding context.
Future<void> showTermsAndConditionsDialog(BuildContext context) {
  final loc = AppLocalizations.of(context)!;
  return showDialog<void>(
    context: context,
    barrierDismissible: true,
    builder: (dialogContext) {
      final theme = Theme.of(dialogContext);
      final colorScheme = theme.colorScheme;
      final screenSize = MediaQuery.of(dialogContext).size;

      // Fixed card dimensions regardless of how much text there is --
      // only the content inside scrolls.
      final cardWidth = screenSize.width * 0.9;
      final cardHeight = (screenSize.height * 0.8).clamp(400.0, 640.0);

      return Dialog(
        backgroundColor: theme.cardColor,
        insetPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        child: SizedBox(
          width: cardWidth,
          height: cardHeight,
          child: Column(
            children: [
              // Fixed header: title + close button never scroll away.
              Container(
                padding: const EdgeInsets.fromLTRB(20, 18, 12, 14),
                decoration: BoxDecoration(
                  border: Border(
                    bottom: BorderSide(color: theme.dividerColor),
                  ),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: Text(
                        loc.termsConditions,
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                          color: colorScheme.onSurface,
                        ),
                      ),
                    ),
                    IconButton(
                      icon: Icon(Icons.close, color: colorScheme.onSurfaceVariant),
                      tooltip: loc.closeButton,
                      onPressed: () => Navigator.of(dialogContext).pop(),
                    ),
                  ],
                ),
              ),
              // Scrollable body: only this part moves.
              Expanded(
                child: Scrollbar(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.fromLTRB(20, 16, 20, 20),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          _termsLastUpdated,
                          style: TextStyle(
                            fontSize: 12,
                            color: colorScheme.onSurfaceVariant,
                          ),
                        ),
                        Text(
                          _termsVersion,
                          style: TextStyle(
                            fontSize: 12,
                            color: colorScheme.onSurfaceVariant,
                          ),
                        ),
                        const SizedBox(height: 14),
                        Text(
                          _termsIntro,
                          style: TextStyle(
                            fontSize: 14,
                            height: 1.5,
                            color: colorScheme.onSurface,
                          ),
                        ),
                        const SizedBox(height: 20),
                        for (final section in _termsSections) ...[
                          Text(
                            section.title,
                            style: TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: colorScheme.primary,
                            ),
                          ),
                          const SizedBox(height: 8),
                          for (final block in section.blocks) ...[
                            if (block.paragraph != null)
                              Padding(
                                padding: const EdgeInsets.only(bottom: 8),
                                child: Text(
                                  block.paragraph!,
                                  style: TextStyle(
                                    fontSize: 14,
                                    height: 1.5,
                                    color: colorScheme.onSurface,
                                  ),
                                ),
                              ),
                            if (block.bullets != null)
                              Padding(
                                padding: const EdgeInsets.only(bottom: 8),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: block.bullets!.map((b) {
                                    return Padding(
                                      padding: const EdgeInsets.only(bottom: 4),
                                      child: Row(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Padding(
                                            padding: const EdgeInsets.only(top: 6, right: 8),
                                            child: Container(
                                              width: 4,
                                              height: 4,
                                              decoration: BoxDecoration(
                                                color: colorScheme.onSurfaceVariant,
                                                shape: BoxShape.circle,
                                              ),
                                            ),
                                          ),
                                          Expanded(
                                            child: Text(
                                              b,
                                              style: TextStyle(
                                                fontSize: 14,
                                                height: 1.5,
                                                color: colorScheme.onSurface,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    );
                                  }).toList(),
                                ),
                              ),
                          ],
                          const SizedBox(height: 12),
                        ],
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      );
    },
  );
}
