// lib/screens/join_group_screen.dart
//
// Phase 4 (Option A) — the invited person enters (or scans) the code
// generated by InviteMemberScreen. On success they're added as a
// "linked" member -- their own health data is untouched, they keep using
// PersonalInfoScreen exactly as before.
//
// Visual style: CustomTextField (widgets/custom_text_field.dart) for the
// code entry, same primary-colored FilledButton as GroupScreen's
// "Create a Group" button.

import 'package:flutter/material.dart';

import '../data/services/backend_locator.dart';
import '../services/auth_service.dart';
import '../services/haptic_service.dart';
import '../widgets/custom_text_field.dart';

class JoinGroupScreen extends StatefulWidget {
  const JoinGroupScreen({super.key});

  @override
  State<JoinGroupScreen> createState() => _JoinGroupScreenState();
}

class _JoinGroupScreenState extends State<JoinGroupScreen> {
  final _authService = AuthService();
  final _groupRepository = BackendLocator.groupRepository;
  final _codeController = TextEditingController();

  bool _submitting = false;
  String? _errorText;

  @override
  void dispose() {
    _codeController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    final code = _codeController.text.trim().toUpperCase();
    if (code.isEmpty) {
      setState(() => _errorText = 'Enter a code');
      return;
    }
    final uid = _authService.currentUser?.uid;
    if (uid == null) return;

    setState(() {
      _submitting = true;
      _errorText = null;
    });

    try {
      await _groupRepository.redeemInvite(code: code, joiningUid: uid);
      if (mounted) {
        Navigator.pop(context, true);
      }
    } catch (e) {
      setState(() {
        _errorText = "That code didn't work. Check it and try again.";
        _submitting = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(title: const Text('Join a Group')),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Enter the code someone shared with you to join their health group.',
                style: TextStyle(fontSize: 14, color: colorScheme.onSurfaceVariant),
              ),
              const SizedBox(height: 20),
              CustomTextField(
                controller: _codeController,
                hintText: 'e.g. AB3D9F2K',
                errorText: _errorText,
                textInputAction: TextInputAction.done,
                onSubmitted: (_) => _submit(),
              ),
              const SizedBox(height: 20),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                  onPressed: _submitting ? null : _submit,
                  style: FilledButton.styleFrom(
                    backgroundColor: colorScheme.primary,
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: _submitting
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                        )
                      : const Text('Join Group'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
